# schema.yaml

bases:
  read:
    url: "https://lm-api-reads.fantasy.espn.com/apis/v3/games"
    method: "GET"

  write:
    url: "https://lm-api-writes.fantasy.espn.com/apis/v3/games"
    method: "POST"


routes:
  league:
    path: "/ffl/seasons/{season}/segments/0/leagues/{league_id}"
    base: "read"

  league_history:
    path: "/ffl/leagueHistory/{league_id}"
    base: "read"

  players:
    path: "/ffl/seasons/{season}/players"
    base: "read"

  transactions:
    path: "/ffl/seasons/{season}/segments/0/leagues/{league_id}/transactions"
    base: "write"


operations:

  league_teams:
    route: "league"
    params:
      view: "mTeam"
    model: "Team"
    response_root: "teams"
    response_form: "list"
    
    # EXAMPLE OF FIELD_MAP (currently not used)
    # field_map:
    #   currentProjectedRank: current_projected_rank
    #   record.overall.pointsFor: record.overall.points_for

  league_teams_historical:
    route: "league_history"
    params:
      view: "mTeam"
    model: "Season"
    # response_root: "teams"
    response_form: "list"

  # position (default and eligible) and name
  players_short:
    route: "players"
    params:
      view: "players_wl"
    model: "Player"
    response_form: "list"

  # less detailed than mMatchup
  # returns boxscore-level info per matchup for entire season specified
  # boxscores:
  #   route: "league"
  #   params:
  #     view: "mBoxscore"
  #   model: "Boxscore"
  #   response_root: "schedule"
  #   response_form: "list"

  # matchups:
  #   route: "league"
  #   params:
  #     view: "mMatchup"
  #   model: "Matchup"
  #   response_root: "schedule"
  #   response_form: "list"

  # mMatchup and mBoxscore, for historical seasons, returns same thing
  matchups_historical:
    route: "league"
    params:
      view: "mMatchup"
    model: "MatchupHistorical"
    response_root: "schedule"
    response_form: "list"

  roster_move:
    route: "transactions"
    model: "RosterMoveResponse"
    response_form: "dict"

  


