# schema.yaml

base_url: "https://lm-api-reads.fantasy.espn.com/apis/v3/games"


routes:
  league:
    path: "/ffl/seasons/{season}/segments/0/leagues/{league_id}"
    method: "GET"

operations:

  league_teams:
    route: "league"
    params:
      view: "mTeam"
    model: "Team"
    response_root: "teams"
    response_form: "list"
    field_map:
      name: name
      currentProjectedRank: current_projected_rank
